#ifndef GULMAYGENERATOR_GLOBAL_H
#define GULMAYGENERATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GULMAYGENERATOR_LIBRARY)
#  define GULMAYGENERATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GULMAYGENERATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GULMAYGENERATOR_GLOBAL_H
