#############################################################################
# Makefile for building: iBEX
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  iBEX.pro
# Template: subdirs
# Command: C:\Qt\5.9.4\msvc2015_64\bin\qmake.exe -o Makefile iBEX.pro -spec win32-msvc
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.9.4\msvc2015_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.9.4\msvc2015_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.9.4\msvc2015_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-launch \
		sub-plugins


sub-launch-qmake_all:  FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	cd launch\ && $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && $(MAKE) -f Makefile qmake_all
sub-launch: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-launch-make_first-ordered: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-launch-make_first: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-launch-all-ordered: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-launch-all: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-launch-clean-ordered: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-launch-clean: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-launch-distclean-ordered: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-launch-distclean: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-launch-install_subtargets-ordered: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-launch-install_subtargets: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-launch-uninstall_subtargets-ordered: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-launch-uninstall_subtargets: FORCE
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-plugins-qmake_all: sub-launch-qmake_all FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	cd plugins\ && $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && $(MAKE) -f Makefile qmake_all
sub-plugins: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile
sub-plugins-make_first-ordered: sub-launch-make_first-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-plugins-make_first: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile 
sub-plugins-all-ordered: sub-launch-all-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-plugins-all: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile all
sub-plugins-clean-ordered: sub-launch-clean-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-plugins-clean: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile clean
sub-plugins-distclean-ordered: sub-launch-distclean-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-plugins-distclean: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile distclean
sub-plugins-install_subtargets-ordered: sub-launch-install_subtargets-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-plugins-install_subtargets: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile install
sub-plugins-uninstall_subtargets-ordered: sub-launch-uninstall_subtargets-ordered  FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall
sub-plugins-uninstall_subtargets: FORCE
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile uninstall

Makefile: iBEX.pro C:\Qt\5.9.4\msvc2015_64\mkspecs\win32-msvc\qmake.conf C:\Qt\5.9.4\msvc2015_64\mkspecs\features\spec_pre.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\common\angle.conf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\common\msvc-desktop.conf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\qconfig.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3danimation.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3danimation_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_core.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_designer.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_egl_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_fb_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gui.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_help.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_location.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_network.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qml.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quick.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sql.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_svg.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_theme_support_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webview.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xml.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\qt_functions.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\qt_config.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\win32-msvc\qmake.conf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\spec_post.prf \
		.qmake.stash \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\exclusive_builds.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\common\msvc-version.conf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\toolchain.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\default_pre.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\win32\default_pre.prf \
		commonconfig.pri \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\resolve_config.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\exclusive_builds_post.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\default_post.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\precompile_header.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\warn_on.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\qmake_use.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\file_copies.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\win32\windows.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\testcase_targets.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\exceptions.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\yacc.prf \
		C:\Qt\5.9.4\msvc2015_64\mkspecs\features\lex.prf \
		iBEX.pro
	$(QMAKE) -o Makefile iBEX.pro -spec win32-msvc
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\spec_pre.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\common\angle.conf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\common\msvc-desktop.conf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\qconfig.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3danimation.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3danimation_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dcore.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dcore_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dextras.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dextras_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dinput.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dinput_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dlogic.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dlogic_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquick.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquick_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickextras_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickinput_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickrender_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3drender.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_3drender_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_accessibility_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axbase.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axbase_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axcontainer.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axcontainer_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axserver.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_axserver_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_bluetooth.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_bluetooth_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_bootstrap_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_concurrent.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_concurrent_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_core.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_core_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_dbus.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_dbus_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_designer.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_designer_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_designercomponents_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_egl_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_fb_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gamepad.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gamepad_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gui.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_gui_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_help.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_help_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_location.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_location_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimedia.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimedia_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_network.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_network_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_nfc.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_nfc_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_opengl.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_opengl_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_openglextensions.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_openglextensions_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_packetprotocol_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_positioning.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_positioning_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_printsupport.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_printsupport_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qml.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qml_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmldebug_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmldevtools_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmltest.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qmltest_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quick.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quick_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickparticles_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_quickwidgets_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_scxml.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_scxml_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sensors.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sensors_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialbus.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialbus_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialport.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_serialport_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sql.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_sql_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_svg.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_svg_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_testlib.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_testlib_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_theme_support_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_uiplugin.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_uitools.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_uitools_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webchannel.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webchannel_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_websockets.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_websockets_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webview.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_webview_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_widgets.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_widgets_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_winextras.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_winextras_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xml.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xml_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\modules\qt_lib_zlib_private.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\qt_functions.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\qt_config.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\win32-msvc\qmake.conf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\spec_post.prf:
.qmake.stash:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\exclusive_builds.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\common\msvc-version.conf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\toolchain.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\default_pre.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\win32\default_pre.prf:
commonconfig.pri:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\resolve_config.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\exclusive_builds_post.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\default_post.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\precompile_header.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\warn_on.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\qmake_use.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\file_copies.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\win32\windows.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\testcase_targets.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\exceptions.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\yacc.prf:
C:\Qt\5.9.4\msvc2015_64\mkspecs\features\lex.prf:
iBEX.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile iBEX.pro -spec win32-msvc

qmake_all: sub-launch-qmake_all sub-plugins-qmake_all FORCE

make_first: sub-launch-make_first-ordered sub-plugins-make_first-ordered  FORCE
all: sub-launch-all-ordered sub-plugins-all-ordered  FORCE
clean: sub-launch-clean-ordered sub-plugins-clean-ordered  FORCE
distclean: sub-launch-distclean-ordered sub-plugins-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-launch-install_subtargets-ordered sub-plugins-install_subtargets-ordered FORCE
uninstall_subtargets: sub-launch-uninstall_subtargets-ordered sub-plugins-uninstall_subtargets-ordered FORCE

sub-launch-debug_ordered:
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
sub-plugins-debug_ordered: sub-launch-debug_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile debug
debug: sub-launch-debug_ordered sub-plugins-debug_ordered

sub-launch-release_ordered:
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
sub-plugins-release_ordered: sub-launch-release_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile release
release: sub-launch-release_ordered sub-plugins-release_ordered

sub-launch-check_ordered:
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
sub-plugins-check_ordered: sub-launch-check_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile check
check: sub-launch-check_ordered sub-plugins-check_ordered

sub-launch-benchmark_ordered:
	@if not exist launch\ mkdir launch\ & if not exist launch\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd launch\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\launch\launch.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
sub-plugins-benchmark_ordered: sub-launch-benchmark_ordered 
	@if not exist plugins\ mkdir plugins\ & if not exist plugins\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd plugins\ && ( if not exist Makefile $(QMAKE) -o Makefile C:\Users\Altay\Documents\Qt\Projects\ibex\plugins\plugins.pro -spec win32-msvc ) && $(MAKE) -f Makefile benchmark
benchmark: sub-launch-benchmark_ordered sub-plugins-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

