#ifndef DELTAB2MOTORDRIVER_GLOBAL_H
#define DELTAB2MOTORDRIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DELTAB2MOTORDRIVER_LIBRARY)
#  define DELTAB2MOTORDRIVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DELTAB2MOTORDRIVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DELTAB2MOTORDRIVER_GLOBAL_H
