#ifndef TELEDYNEDETECTOR_GLOBAL_H
#define TELEDYNEDETECTOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TELEDYNEDETECTOR_LIBRARY)
#  define TELEDYNEDETECTORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TELEDYNEDETECTORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TELEDYNEDETECTOR_GLOBAL_H
