#ifndef BUTTERWORTHLOWPASSFILTER_GLOBAL_H
#define BUTTERWORTHLOWPASSFILTER_GLOBAL_H
#include <QtCore/qglobal.h>

#if defined(BUTTERWORTHLOWPASSFILTER_LIBRARY)
#  define BUTTERWORTHLOWPASSFILTER_EXPORT Q_DECL_EXPORT
#else
#  define BUTTERWORTHLOWPASSFILTER_EXPORT Q_DECL_IMPORT
#endif
#endif // BUTTERWORTHLOWPASSFILTER_GLOBAL_H
